version: '3'

services:
  redis:
    image: redis:alpine
    ports:
    - 6379:6379
  mongodb:
    image: mongo:latest
    container_name: mongo-replica-set
    expose:
      - 27017
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all"]
volumes:
  mongodb_data:
